os: linux
sudo: required
dist: trusty
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
- '6'
- '7'
- '8'
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# - sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- jdk_switcher use oraclejdk8
- yarn run test
- yarn run build
- mv dist barf
- tar -czvf barf-$TRAVIS_BRANCH.tar.gz barf
- md5sum barf-$TRAVIS_BRANCH.tar.gz > barf-$TRAVIS_BRANCH.tar.gz.md5
deploy:
  provider: releases
  api_key:
    secure: W3m3TR9QRKmwpd5Y/Y7l9CNjaYRWq7NONlUrQcPs2AGe41K6Ge14ZhW2pdvrMKTPesNtLCpZ5IQb3qsg1aS02x2Ie3yarBCRF/nRpAQwZJg95tMEGW0bTOLi9eFsjToqCO01m5fVy0ESL02nW5SS8XMuv2TJfLjhI0etl7I5vKJzKY3rYbV/NjUxITgwe1Ay7OkUAUTBSgHl2BagwVNvoabn1teHN2HEPDVNjKutZj2oQgnSHr4XqGRvQRR8fqDazoEl3jiZ57tGJXwBN9+9NcxZxtLGUro1pGd1jrjvp/lSdIhVL9VVrndhKKorr0R8i/OTQMIJ+HKYypYdROOiC/R7+XguZJ40nK3OGR3TlWu0BOl1apzshWXqeqtIEZesE/1W/Zec6SzTTu9klByMidaJXJzDIlDW/QFa4yDoHLa2FAO8oN8Xx+p+ZOg/D6E3iiXwlIi/53dRXlxQjsIzk2xx/V+Gavi1QsdArgcXjxyV7F5bx2yQ37rQIu5xNDAmZRE5u6ozzQ8H7hK0otesaUAkmEQYxIUgERuKi8psenMLMpO9bkxX01AwE6oxsvfBMAzhCFUR2wNWW8q0SWDeQqOAvxd+AiftBcK4vkSSnHq4c6kYFHq/BQTaPKbbhYJshdkKbAjBcM8AKtd5dvJoZveZSBRN+UXqd+DA7prn5i8=
  file:
    - barf-$TRAVIS_BRANCH.tar.gz
    - barf-$TRAVIS_BRANCH.tar.gz.md5
  skip_cleanup: true
  on:
    repo: dahrens/barf
    tags: true
