export const SET_VERSION = 'SET_VERSION'
export const WRITE_SETTINGS = 'WRITE_SETTINGS'

export const SELECT_DOG = 'SELECT_DOG'
export const INSERT_DOG = 'INSERT_DOG'
export const REMOVE_DOG = 'REMOVE_DOG'
export const UPDATE_DOG = 'UPDATE_DOG'

export const INSERT_INGREDIENT = 'INSERT_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const STASH_INGREDIENT = 'STASH_INGREDIENT'

export const UPDATE_PLAN_CATEGORY_DISTRIBUTION = 'UPDATE_PLAN_CATEGORY_DISTRIBUTION'
export const UPDATE_PLAN_DISTRIBUTION = 'UPDATE_PLAN_DISTRIBUTION'
export const ADD_OR_UPDATE_DAY_ALLOCATION = 'ADD_OR_UPDATE_DAY_ALLOCATION'
export const REMOVE_DAY_ALLOCATION = 'REMOVE_DAY_ALLOCATION'
export const UPDATE_PLAN_ALLOCATION = 'UPDATE_PLAN_ALLOCATION'

export const SCHEDULE_MEAL = 'SCHEDULE_MEAL'
export const REMOVE_SCHEDULED_MEAL = 'REMOVE_SCHEDULED_MEAL'

export const INSERT_NOTIFICATION = 'INSERT_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
